Shooter up/down basic commands created
koibots8230/Anglerfish-2024 pull request #4
Opened 2024-01-18 21:33 UTC by GrantS-R

- [x] Shooter up/down constructed
- [x] Shooter up/down basic setters created
- [x] Shooter up/down basic getters created
- [x] Shooter up/down basic commands created
- [ ] Shooter up/down initialize created (I assume this is needed so I'm putting it here)
- [ ] Shooter up/down added to main robot code

2024-01-18 21:46 UTC, JakeStew81 requested changes

2024-01-18 21:46 UTC, JakeStew81 commented on src/main/java/com/koibots/robot/subsystems/ShooterPositionSubsystem.java
> +    public void setShooterPosition(double desiredPosition) {
Deadzone please! Otherwise itll just go back and forth over the setpoint

2024-01-18 21:46 UTC, JakeStew81 commented on src/main/java/com/koibots/robot/subsystems/ShooterPositionSubsystem.java
> +            canLoad = true;
What's this canLoad thing for? You never use it

2024-01-18 21:46 UTC, JakeStew81 commented on src/main/java/com/koibots/robot/subsystems/ShooterPositionSubsystem.java
> +    public void loadNote() {
? Explain the purpose of this please

2024-01-18 21:55 UTC, GrantS-R commented on src/main/java/com/koibots/robot/subsystems/ShooterPositionSubsystem.java
> +    public void loadNote() {
I wanted to make something separate for loading the note, since I know that's the one hard stop we have. If you want me to make it all 1 command I can do that, just tell me.

2024-01-19 21:43 UTC, JakeStew81 commented on src/main/java/com/koibots/robot/subsystems/ShooterPositionSubsystem.java
> +    public void loadNote() {
There is no hard stop on the shooter anywhere, it can go a full 360 degrees

2024-01-20 16:10 UTC, GrantS-R commented on src/main/java/com/koibots/robot/subsystems/ShooterPositionSubsystem.java
> +    public void loadNote() {
the `canLoad` and `loadNote()` is to make sure that you cant run whatever the program to put a note in the intake into the shooter. it doesnt do anything right now, but I think it will be important later on.

2024-01-29 14:42 UTC, CalebNeal07 commented on src/main/java/com/koibots/robot/subsystems/ShooterPivot.java
> -        shooterPivotMotor.setIdleMode(IdleMode.kBrake);
Change this to take a boolean and set it to coast if false and brake if true, and `setShooterPositionModeBreak` should be `setBrake`.

2024-01-29 14:42 UTC, CalebNeal07 commented on src/main/java/com/koibots/robot/subsystems/ShooterPivot.java
>      //getters
If a method isn't being used they're is no reason for it to exist.

2024-01-29 14:42 UTC, CalebNeal07 commented on src/main/java/com/koibots/robot/subsystems/ShooterPivotIO.java
> +
Shooter Pivot is evident from context so you don't need it in variable names

2024-01-29 14:42 UTC, CalebNeal07 commented on src/main/java/com/koibots/robot/subsystems/ShooterPivotIOSparkMax.java
> +        shooterPivotEncoder.setZeroOffset(0);
Add a constant here not just 0

2024-01-29 14:42 UTC, CalebNeal07 commented on src/main/java/com/koibots/robot/subsystems/ShooterPivotIO.java
> +    public static class ShooterPivotIOInputs {
Add the shooter pivot motor's current voltage velocity here

2024-01-30 13:24 UTC, JakeStew81 requested changes

2024-01-30 13:24 UTC, JakeStew81 commented on src/main/java/com/koibots/robot/Constants.java
> +    public static final int SHOOTER_PIVOT_MOTOR = 0;
Have these in their own `ShooterConstants` subclass, which also lets you remove shooter from all the names

2024-01-30 13:24 UTC, JakeStew81 commented on src/main/java/com/koibots/robot/subsystems/ShooterPivot/ShooterPivot.java
> +    public void resetShooterMotorPosition() {
Since you're using it in absolute encoder mode, you shouldn't have to zero it in code, its just something you do with rev hardware client every once in a while

2024-01-30 21:09 UTC, JakeStew81 requested changes

2024-01-30 21:09 UTC, JakeStew81 commented on src/main/java/com/koibots/robot/subsystems/ShooterPivot/ShooterPivot.java
> +    public void setShooterPivotMode(boolean mode) {
Maybe rename mode to something more clear like `isBreak`

2024-01-30 21:09 UTC, JakeStew81 commented on src/main/java/com/koibots/robot/subsystems/ShooterPivot/ShooterPivotIOSparkMax.java
> +        shooterPivotEncoder.setZeroOffset(0);
You do not need to set the zero offset in code, its something that happens in the rev hardware client every once in a while

2024-02-22 17:38 UTC, closed without merging